CREATE TABLE SAMPLE (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL
);

CREATE TABLE QRTZ_CALENDARS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  CALENDAR_NAME VARCHAR(200) NOT NULL,
  CALENDAR BLOB NOT NULL
);

CREATE TABLE QRTZ_CRON_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(150) NOT NULL,
  TRIGGER_GROUP VARCHAR(150) NOT NULL,
  CRON_EXPRESSION VARCHAR(120) NOT NULL,
  TIME_ZONE_ID VARCHAR(80) NULL
);

CREATE TABLE QRTZ_FIRED_TRIGGERS (
	SCHED_NAME VARCHAR(120) NOT NULL,
	ENTRY_ID VARCHAR(140) NOT NULL,
	TRIGGER_NAME VARCHAR(150) NOT NULL,
	TRIGGER_GROUP VARCHAR(150) NOT NULL,
	INSTANCE_NAME VARCHAR(200) NOT NULL,
	FIRED_TIME BIGINT NOT NULL,
	SCHED_TIME BIGINT NOT NULL,
	PRIORITY INTEGER NOT NULL,
	STATE VARCHAR(16) NOT NULL,
	JOB_NAME VARCHAR(150) NULL,
	JOB_GROUP VARCHAR(150) NULL,
	IS_NONCONCURRENT BOOLEAN NULL,
	REQUESTS_RECOVERY BOOLEAN NULL
);

CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_GROUP VARCHAR(150) NOT NULL 
);

CREATE TABLE QRTZ_SCHEDULER_STATE (
  SCHED_NAME VARCHAR(120) NOT NULL,
  INSTANCE_NAME VARCHAR(200) NOT NULL,
  LAST_CHECKIN_TIME BIGINT NOT NULL,
  CHECKIN_INTERVAL BIGINT NOT NULL
);

CREATE TABLE QRTZ_LOCKS (
	SCHED_NAME VARCHAR(120) NOT NULL,
	LOCK_NAME VARCHAR(40) NOT NULL
);

CREATE TABLE QRTZ_JOB_DETAILS (
	SCHED_NAME VARCHAR(120) NOT NULL,
	JOB_NAME VARCHAR(150) NOT NULL,
	JOB_GROUP VARCHAR(150) NOT NULL,
	DESCRIPTION VARCHAR(250),
	JOB_CLASS_NAME VARCHAR(250) NOT NULL,
	IS_DURABLE BOOLEAN NOT NULL,
	IS_NONCONCURRENT BOOLEAN NOT NULL,
	IS_UPDATE_DATA BOOLEAN NOT NULL,
	REQUESTS_RECOVERY VARCHAR(100) NOT NULL,
	JOB_DATA BLOB NOT NULL
);

CREATE TABLE QRTZ_SIMPLE_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(150) NOT NULL,
  TRIGGER_GROUP VARCHAR(150) NOT NULL,
  REPEAT_COUNT INTEGER NOT NULL,
  REPEAT_INTERVAL BIGINT NOT NULL,
  TIMES_TRIGGERED INTEGER NOT NULL
);

CREATE TABLE QRTZ_SIMPROP_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL,
  TRIGGER_NAME VARCHAR(150) NOT NULL,
  TRIGGER_GROUP VARCHAR(150) NOT NULL,
  STR_PROP_1 VARCHAR(512) NULL,
  STR_PROP_2 VARCHAR(512) NULL,
  STR_PROP_3 VARCHAR(512) NULL,
  INT_PROP_1 INTEGER NULL,
  INT_PROP_2 INTEGER NULL,
  LONG_PROP_1 BIGINT NULL,
  LONG_PROP_2 BIGINT NULL,
  DEC_PROP_1 NUMERIC(13,4) NULL,
  DEC_PROP_2 NUMERIC(13,4) NULL,
  BOOL_PROP_1 BOOLEAN NULL,
  BOOL_PROP_2 BOOLEAN NULL,
  TIME_ZONE_ID VARCHAR(80) NULL 
);

CREATE TABLE QRTZ_BLOB_TRIGGERS (
	SCHED_NAME VARCHAR(120) NOT NULL,
	TRIGGER_NAME VARCHAR(150) NOT NULL,
	TRIGGER_GROUP VARCHAR(150) NOT NULL,
	BLOB_DATA BLOB
);

CREATE TABLE QRTZ_TRIGGERS (
	SCHED_NAME VARCHAR(120) NOT NULL,
	TRIGGER_NAME VARCHAR(150) NOT NULL,
	TRIGGER_GROUP VARCHAR(150) NOT NULL,
	JOB_NAME VARCHAR(150) NOT NULL,
	JOB_GROUP VARCHAR(150) NOT NULL,
	DESCRIPTION VARCHAR(250) NULL,
	NEXT_FIRE_TIME BIGINT NULL,
	PREV_FIRE_TIME BIGINT NULL,
	PRIORITY INTEGER NULL,
	TRIGGER_STATE VARCHAR(16) NULL,
	TRIGGER_TYPE VARCHAR(8) NULL,
	START_TIME BIGINT NULL,
	END_TIME BIGINT NULL,
	CALENDAR_NAME VARCHAR(200) NULL,
	MISFIRE_INSTR INTEGER NULL,
	JOB_DATA BLOB
);
